- name: Configuring {{ component }} server
  ansible.builtin.import_role:
    name: common
    tasks_from: redis_setup.yaml

- name: Allowing on all ports
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Protected mode from yes to no
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: 'protected-mode no'

- name: Start and enable service
  ansible.builtin.include_role:
    name: common
    tasks_from: redis_setup.yaml