- name: Copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongo
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Allowing remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start and enable the service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes