- name: Configuring {{ component }} service
  ansible.builtin.include_role:
    name: common
    tasks_from: nginx.yaml

- name: remove default frontend code
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create usr/share/nginx/html/ directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Remove existing existing frontend application
  ansible.builtin.file:
    path: /tmp/frontend.zip
    state: absent

- name: Download latest frontend application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: Unzip the file
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Updating new nginx conf file
  ansible.builtin.copy:
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: Start and enable service
  ansible.builtin.include_role:
    name: common
    tasks_from: service-setup.yaml