- name: Configuring {{ component }} server
  ansible.builtin.include_role:
    name: common
    tasks_from: mysql.yaml

- name: Start and enable service
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set root password
  community.mysql.mysql_user:
    user: root
    password: "RoboShop@1"
    host: "%"