- name: Configuring {{ component }} server
  ansible.builtin.include_role:
    name: common
    tasks_from: mysql.yaml

- name: Start and enable service
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setting root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1