- name: Disabling existing nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable nodejs version 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Create roboshop system user
  ansible.builtin.user:
    name: roboshop
    state: present
    system: yes
    shell: /sbin/nologin
    comment: "roboshop system user"
    home: /app

- name: Removing /app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Remove existing catalogue application
  ansible.builtin.file:
    path: /tmp/catalogue.zip
    state: absent

- name: Download the catalogue application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: Unzip catalogue file 
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install dependencies
  community.general.npm:
    path: /app

- name: Create systemd service for catalogue application
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: Daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: Copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongo client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: Connect to database
  ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: Load database
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: Start and enable service
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes