- name: Create roboshop system user
  ansible.builtin.user:
    name: roboshop
    state: present
    system: yes
    shell: /sbin/nologin
    comment: "roboshop system user"
    home: /app

- name: Removing /app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Remove existing {{ component }} application
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: Download the {{ component }} application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: Unzip {{ component }} file 
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes