- name: Create systemd service for {{ component }} application
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service
  notify: Daemon-reload
