- name: Disabling existing nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable nodejs version 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Install dependencies
  community.general.npm:
    path: /app