- name: Disabling existing redis version
  ansible.builtin.command: dnf module disable redis -y

- name: Enabling redis version 7 
  ansible.builtin.command: dnf module enable redis:7 -y

- name: Installing redis server
  ansible.builtin.package:
    name: redis
    state: present