- name: App setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup.yaml

- name: NodeJS installation
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yaml

- name: Creating {{ component }} system service 
  ansible.builtin.include_role:
    name: common
    tasks_from: daemon-service.yaml

- name: Start and enable {{ component }} service
  ansible.builtin.include_role:
    name: common
    tasks_from: service-setup.yaml